---
grails:
    profile: rest-api
    codegen:
        defaultPackage: mobix.server
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    dbCreate: ''
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect

environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost/lx_mobix?autoReconnect=false
            username: root
            password: sys
    test:
        dataSource:
            dbCreate: create-drop
            pooled: true
            jmxExport: true
            driverClassName: org.h2.Driver
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            username: sNa
            password:
    production:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://10.10.1.228/lx_mobix?autoReconnect=false
            username: root
            password: sys
            properties:
                maxActive: 10
                maxIdle: 10
                minIdle: 3
                initialSize: 3
                minEvictableIdleTimeMillis: 1800000
                timeBetweenEvictionRunsMillis: 1800000
                numTestsPerEvictionRun: 3
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: true
                maxWait: 10000
                validationQuery: 'SELECT 1'
                validationQueryTimeout: 3
                validationInterval: 15000
    certificacion:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost/lx_mobix_dev?autoReconnect=false
            username: root
            password: sys
            properties:
                maxActive: 10
                maxIdle: 10
                minIdle: 3
                initialSize: 3
                minEvictableIdleTimeMillis: 1800000
                timeBetweenEvictionRunsMillis: 1800000
                numTestsPerEvictionRun: 3
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: true
                maxWait: 10000
                validationQuery: 'SELECT 1'
                validationQueryTimeout: 3
                validationInterval: 15000
---
server:
  port: 9795
  contextPath: /mobix
---
environments:
    certificacion:
        server:
            port: 9499

---
grails:
    cors:
        enabled: true
---
environments:
  development:
    siipapx:
      cxp:
        cfdisDir: /Users/rubencancino/Documents/mobix/cfdis-carga
  production:
    siipapx:
      cxp:
        cfdisDir: /home/mobix/cfdProv
---
